/* Service Worker — SneakerMania (PWA / modo offline)
   Código/navegación: network-first para no mostrar una versión vieja después
   de un deploy. Supabase/Auth/R2 externos nunca se cachean. */
const CACHE='ses-static-v38';
const CORE=['./','./manifest.json','./styles/main.css','./styles/fixes.css'];
async function stripRedirect(res){if(!res||!res.redirected)return res;const body=await res.blob();return new Response(body,{status:res.status,statusText:res.statusText,headers:res.headers});}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()).then(()=>self.clients.matchAll({type:'window'}).then(arr=>arr.forEach(c=>c.postMessage({type:'SW_UPDATED'})))));});
self.addEventListener('fetch',e=>{const req=e.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==self.location.origin)return;if(url.pathname.includes('/functions/')||url.pathname.includes('/rest/')||url.pathname.includes('/auth/'))return;
  if(req.mode==='navigate'){e.respondWith((async()=>{try{const res=await fetch('./',{redirect:'follow',cache:'no-store'});const clean=await stripRedirect(res);if(clean&&clean.status===200){const cache=await caches.open(CACHE);cache.put('./',clean.clone()).catch(()=>{});}return clean;}catch(_){const fallback=await caches.match('./');return fallback?stripRedirect(fallback):Response.error();}})());return;}
  e.respondWith(caches.open(CACHE).then(async cache=>{const cached=await cache.match(req);const cachedOk=cached&&cached.status===200&&!cached.redirected?cached:null;try{const res=await fetch(req,{redirect:'follow',cache:'no-cache'});const clean=await stripRedirect(res);if(clean&&clean.status===200&&clean.type==='basic')cache.put(req,clean.clone()).catch(()=>{});return clean||cachedOk;}catch(_){return cachedOk||Response.error();}}));
});
self.addEventListener('push',e=>{let data={};try{data=e.data?e.data.json():{};}catch(err){data={titulo:'SneakerMania',mensaje:e.data?e.data.text():''};}const titulo=data.titulo||'SneakerMania';const opciones={body:data.mensaje||'',icon:data.icono||'./assets/icon-192.png',badge:'./assets/icon-192.png',tag:data.tag||('ses-push-'+Date.now()),data:{url:data.url||'./'},requireInteraction:false,silent:false,vibrate:[200,80,200]};e.waitUntil(self.registration.showNotification(titulo,opciones));});
self.addEventListener('notificationclick',e=>{e.notification.close();const url=e.notification.data&&e.notification.data.url||'./';e.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(arr=>{const existing=arr.find(c=>'focus'in c);if(existing)return existing.focus();return self.clients.openWindow(url);}));});
self.addEventListener('pushsubscriptionchange',e=>{e.waitUntil(self.clients.matchAll({type:'window',includeUncontrolled:true}).then(arr=>arr.forEach(c=>c.postMessage({type:'PUSH_SUBSCRIPTION_CHANGED'}))));});
